# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\race.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RaceWindow(object):
    def setupUi(self, RaceWindow):
        RaceWindow.setObjectName("RaceWindow")
        RaceWindow.resize(393, 232)
        self.centralwidget = QtWidgets.QWidget(RaceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 208))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(3)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 6, 31, 16))
        self.label.setObjectName("label")
        self.pos_label_p1 = QtWidgets.QLabel(self.frame)
        self.pos_label_p1.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.pos_label_p1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pos_label_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p1.setObjectName("pos_label_p1")
        self.pos_label_p2 = QtWidgets.QLabel(self.frame)
        self.pos_label_p2.setGeometry(QtCore.QRect(10, 54, 31, 16))
        self.pos_label_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p2.setObjectName("pos_label_p2")
        self.pos_label_p3 = QtWidgets.QLabel(self.frame)
        self.pos_label_p3.setGeometry(QtCore.QRect(10, 78, 31, 16))
        self.pos_label_p3.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p3.setObjectName("pos_label_p3")
        self.pos_label_p4 = QtWidgets.QLabel(self.frame)
        self.pos_label_p4.setGeometry(QtCore.QRect(10, 102, 31, 16))
        self.pos_label_p4.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p4.setObjectName("pos_label_p4")
        self.pos_label_p5 = QtWidgets.QLabel(self.frame)
        self.pos_label_p5.setGeometry(QtCore.QRect(10, 126, 31, 16))
        self.pos_label_p5.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p5.setObjectName("pos_label_p5")
        self.pos_label_p6 = QtWidgets.QLabel(self.frame)
        self.pos_label_p6.setGeometry(QtCore.QRect(10, 150, 31, 16))
        self.pos_label_p6.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p6.setObjectName("pos_label_p6")
        self.pos_label_p7 = QtWidgets.QLabel(self.frame)
        self.pos_label_p7.setGeometry(QtCore.QRect(10, 174, 31, 16))
        self.pos_label_p7.setAlignment(QtCore.Qt.AlignCenter)
        self.pos_label_p7.setObjectName("pos_label_p7")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 18, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 601, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(0, 66, 601, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(0, 90, 601, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(0, 114, 601, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(0, 138, 601, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(0, 162, 601, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(0, 186, 601, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setGeometry(QtCore.QRect(33, 24, 20, 169))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 6, 61, 16))
        self.label_2.setObjectName("label_2")
        self.name_label_p1 = QtWidgets.QLabel(self.frame)
        self.name_label_p1.setGeometry(QtCore.QRect(48, 24, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p1.setFont(font)
        self.name_label_p1.setObjectName("name_label_p1")
        self.name_label_p2 = QtWidgets.QLabel(self.frame)
        self.name_label_p2.setGeometry(QtCore.QRect(48, 48, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p2.setFont(font)
        self.name_label_p2.setObjectName("name_label_p2")
        self.name_label_p3 = QtWidgets.QLabel(self.frame)
        self.name_label_p3.setGeometry(QtCore.QRect(48, 72, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p3.setFont(font)
        self.name_label_p3.setObjectName("name_label_p3")
        self.name_label_p4 = QtWidgets.QLabel(self.frame)
        self.name_label_p4.setGeometry(QtCore.QRect(48, 96, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p4.setFont(font)
        self.name_label_p4.setObjectName("name_label_p4")
        self.name_label_p5 = QtWidgets.QLabel(self.frame)
        self.name_label_p5.setGeometry(QtCore.QRect(48, 120, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p5.setFont(font)
        self.name_label_p5.setObjectName("name_label_p5")
        self.name_label_p6 = QtWidgets.QLabel(self.frame)
        self.name_label_p6.setGeometry(QtCore.QRect(48, 144, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p6.setFont(font)
        self.name_label_p6.setObjectName("name_label_p6")
        self.name_label_p7 = QtWidgets.QLabel(self.frame)
        self.name_label_p7.setGeometry(QtCore.QRect(48, 168, 181, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label_p7.setFont(font)
        self.name_label_p7.setObjectName("name_label_p7")
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setGeometry(QtCore.QRect(216, 24, 20, 169))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(234, 6, 79, 16))
        self.label_10.setObjectName("label_10")
        self.lap_label_p1 = QtWidgets.QLabel(self.frame)
        self.lap_label_p1.setGeometry(QtCore.QRect(234, 30, 61, 16))
        self.lap_label_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p1.setObjectName("lap_label_p1")
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setGeometry(QtCore.QRect(288, 24, 20, 169))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(306, 6, 85, 16))
        self.label_12.setObjectName("label_12")
        self.lap_diff_p1 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p1.setGeometry(QtCore.QRect(306, 24, 67, 19))
        self.lap_diff_p1.setToolTipDuration(0)
        self.lap_diff_p1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p1.setObjectName("lap_diff_p1")
        self.lap_label_p2 = QtWidgets.QLabel(self.frame)
        self.lap_label_p2.setGeometry(QtCore.QRect(234, 54, 61, 16))
        self.lap_label_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p2.setObjectName("lap_label_p2")
        self.lap_label_p3 = QtWidgets.QLabel(self.frame)
        self.lap_label_p3.setGeometry(QtCore.QRect(234, 78, 61, 16))
        self.lap_label_p3.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p3.setObjectName("lap_label_p3")
        self.lap_label_p4 = QtWidgets.QLabel(self.frame)
        self.lap_label_p4.setGeometry(QtCore.QRect(234, 102, 61, 16))
        self.lap_label_p4.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p4.setObjectName("lap_label_p4")
        self.lap_label_p5 = QtWidgets.QLabel(self.frame)
        self.lap_label_p5.setGeometry(QtCore.QRect(234, 126, 61, 16))
        self.lap_label_p5.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p5.setObjectName("lap_label_p5")
        self.lap_label_p6 = QtWidgets.QLabel(self.frame)
        self.lap_label_p6.setGeometry(QtCore.QRect(234, 150, 61, 16))
        self.lap_label_p6.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p6.setObjectName("lap_label_p6")
        self.lap_label_p7 = QtWidgets.QLabel(self.frame)
        self.lap_label_p7.setGeometry(QtCore.QRect(234, 174, 61, 16))
        self.lap_label_p7.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_label_p7.setObjectName("lap_label_p7")
        self.lap_diff_p2 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p2.setGeometry(QtCore.QRect(306, 48, 67, 25))
        self.lap_diff_p2.setToolTipDuration(0)
        self.lap_diff_p2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p2.setObjectName("lap_diff_p2")
        self.lap_diff_p3 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p3.setGeometry(QtCore.QRect(306, 78, 67, 19))
        self.lap_diff_p3.setToolTipDuration(0)
        self.lap_diff_p3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p3.setObjectName("lap_diff_p3")
        self.lap_diff_p4 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p4.setGeometry(QtCore.QRect(306, 102, 67, 19))
        self.lap_diff_p4.setToolTipDuration(0)
        self.lap_diff_p4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p4.setObjectName("lap_diff_p4")
        self.lap_diff_p5 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p5.setGeometry(QtCore.QRect(306, 126, 67, 19))
        self.lap_diff_p5.setToolTipDuration(0)
        self.lap_diff_p5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p5.setObjectName("lap_diff_p5")
        self.lap_diff_p6 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p6.setGeometry(QtCore.QRect(306, 150, 67, 19))
        self.lap_diff_p6.setToolTipDuration(0)
        self.lap_diff_p6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p6.setObjectName("lap_diff_p6")
        self.lap_diff_p7 = QtWidgets.QLabel(self.frame)
        self.lap_diff_p7.setGeometry(QtCore.QRect(306, 174, 67, 19))
        self.lap_diff_p7.setToolTipDuration(0)
        self.lap_diff_p7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lap_diff_p7.setObjectName("lap_diff_p7")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(0, 198, 307, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(312, 198, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.quit_button.setFont(font)
        self.quit_button.setObjectName("quit_button")
        RaceWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RaceWindow)
        QtCore.QMetaObject.connectSlotsByName(RaceWindow)

    def retranslateUi(self, RaceWindow):
        _translate = QtCore.QCoreApplication.translate
        RaceWindow.setWindowTitle(_translate("RaceWindow", "MainWindow"))
        self.label.setText(_translate("RaceWindow", "POS"))
        self.pos_label_p1.setText(_translate("RaceWindow", "1"))
        self.pos_label_p2.setText(_translate("RaceWindow", "2"))
        self.pos_label_p3.setText(_translate("RaceWindow", "3"))
        self.pos_label_p4.setText(_translate("RaceWindow", "4"))
        self.pos_label_p5.setText(_translate("RaceWindow", "5"))
        self.pos_label_p6.setText(_translate("RaceWindow", "6"))
        self.pos_label_p7.setText(_translate("RaceWindow", "7"))
        self.label_2.setText(_translate("RaceWindow", "Name"))
        self.name_label_p1.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p2.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p3.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p4.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p5.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p6.setText(_translate("RaceWindow", "-----------------------------"))
        self.name_label_p7.setText(_translate("RaceWindow", "-----------------------------"))
        self.label_10.setText(_translate("RaceWindow", "Last Lap"))
        self.lap_label_p1.setText(_translate("RaceWindow", "0:00.00"))
        self.label_12.setText(_translate("RaceWindow", "Difference"))
        self.lap_diff_p1.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_label_p2.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_label_p3.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_label_p4.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_label_p5.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_label_p6.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_label_p7.setText(_translate("RaceWindow", "0:00.00"))
        self.lap_diff_p2.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_diff_p3.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_diff_p4.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_diff_p5.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_diff_p6.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.lap_diff_p7.setText(_translate("RaceWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">+0.32</span></p></body></html>"))
        self.quit_button.setText(_translate("RaceWindow", "Quit"))

